# Generated by Django 5.2.6 on 2025-11-02 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('aroma', models.PositiveSmallIntegerField()),
                ('sabor', models.PositiveSmallIntegerField()),
                ('cuerpo', models.PositiveSmallIntegerField()),
                ('apariencia', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.beer')),
            ],
        ),
    ]
