# Generated by Django 5.2.6 on 2025-11-09 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report_thread_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='brand',
            field=models.CharField(blank=True, max_length=120, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='review',
            name='brewery_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cervecería Productora'),
        ),
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='review_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.review')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
