# Generated by Django 5.2.6 on 2025-11-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_options_alter_thread_options_post_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='beer_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
